name: Update Song Count

on:
  # 手动触发
  workflow_dispatch:
  # 当 all.json 更改时触发
  push:
    paths:
      - 'all.json'
    branches:
      - main

jobs:
  update-count:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # 从 main 分支检出代码
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Create song statistics files
        run: |
          node -e '
          const fs = require("fs");
          const songs = JSON.parse(fs.readFileSync("all.json", "utf8"));
          
          // 按 order 排序所有歌曲
          const sortedSongs = [...songs].sort((a, b) => a.order - b.order);
          
          // 1. 生成统计数据
          const count = {
            total: songs.length,
            paid: songs.filter(song => song.is_paid).length,
            free: songs.filter(song => !song.is_paid).length,
            genres: {}
          };
          
          // 统计每个流派的数量
          songs.forEach(song => {
            count.genres[song.genre] = (count.genres[song.genre] || 0) + 1;
          });
          
          // 写入统计数据
          fs.writeFileSync("song-stats.json", JSON.stringify(count, null, 4));
          
          // 2. 生成全部歌曲排序文件
          fs.writeFileSync("song-all.json", JSON.stringify(sortedSongs, null, 4));
          '
          
      - name: Config Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Switch to data branch
        run: |
          git fetch origin
          git checkout data 2>/dev/null || git checkout -b data
          git reset --hard origin/data || true
          
      - name: Copy and commit files
        run: |
          # 复制需要的文件
          cp ../all.json .
          cp ../song-stats.json .
          cp ../song-all.json .
          
          # 提交更改
          git add all.json song-stats.json song-all.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "更新歌曲统计数据" && git push origin data) 